### PR TITLE
Whitebox level1

### PR DESCRIPTION
**Pull request by HenrikHokby**
Level 1 should now be feature complete with lighting, new enemies, skybox and visual effects

### CODE REVIEW

**Review by Viktorb9 — CHANGES_REQUESTED** [review]
Looks great! However, the checkpoint after the the train station makes the player face the wrong way and needs to be fixed.

**Review by shaeeee — CHANGES_REQUESTED** [review]
Here are some places you can jump out of the level:
image
image
image

**Review by shaeeee — APPROVED** [review]
V good

**Comment by ErikPilstrom** [comment]
Fixing with the prefab method

**Pull request closed without merging**
