### PR TITLE
The numbers, Mason, what do they mean!?

### PR DESCRIPTION
**Pull request by ErikPilstrom**
This branch adds the function RandomInCone() to EnemyWeaponBase.cs to generate a randomized vector inside a cone around a central input axis, within a certain angle from the axis.

- Fuck this maths with a blunt spoon, honestly. This might be some of the hardest work I've ever done trying to figure this shit out.
- But hey, it works! We now have a new spread function we can apply to shots from our weapons, that will be 100% consistent, is based off a given input angle and an input axis as the centre of the cone. The angle determines the arc of a cone subtraction from a sphere around a given input axis (yeah, you're confused too now, huh?)
- The function plots randomly and uniformly distributed points on the spherical cap defined by the plane that is parallel to the base of the cone, giving us a vector from whatever origin point we want to the randomly plotted point, based on our input axis vector and the desired angle.
- The function should be given a normalized input axis vector and an angle between 0 and 360. A spread of 0 will make the function return the input axis and a spread of 360 will make the function return a vector with a random heading inside a unit 2-sphere (a sphere in 3 dimensions with a radius of 1). The returned vector can then be multiplied by whatever scalar we want to stretch how far it projects (like an attack range).

- The MAJOR advantage of this function over the old AddSpread that we have in WeaponBase.cs is that THIS function is independent of the distance to the target, meaning that no matter how far or close a target is, the spread will always be the same from the origin to infinity. The result is that attacks onto a target close to the origin point have a lower chance to miss, and attacks further away have a higher chance to miss.
- Another significant advantage is that this function takes a regular angle in degrees as one of its parameters, making enemy rebalance significantly more transparent and a lot easier to deal with.

Play around, have fun, don't worry about my blood, sweat, and tears :)

### CODE REVIEW

**Review by shaeeee — CHANGES_REQUESTED** [review]
It looks good but this yeeting issue when I move really close to the enemy needs to be fixed. It only happens once every time I close the distance, once I am in that close range it doesn't happen until I back off and close in again.

**Comment by ErikPilstrom** [comment]
Updates to branch adds:
- Temporary and crude fix to the requested bugfix.
- Fixes the enemy destruction issues
- Changes to Drone and Turret prefab to work within the current system

**Review by shaeeee — CHANGES_REQUESTED** [review]
Issue appears to be solved and everything else seems to be working still, but please remove the `Debug.Log()` prints on enemy attack.

**Review by shaeeee — APPROVED** [review]
(❁´◡`❁)

**Pull request merged**
