### PR TITLE
made crosshair white

### LINKED ISSUE #141: Crosshair is not very visible
Crosshair color needs to be replaced with something more visible. Ref below.
image

### PR DESCRIPTION
**Pull request by kimcodekill**
fixes #141

### CODE REVIEW

**Review by shaeeee — APPROVED** [review]
Works well, is more visible than before. Making it white of course means you'll have the same issue against white bg's, but it looks like we'll run into that less compared to using a black reticle, so approved.

**Comment by kimcodekill** [comment]
@shaeeee as the crosshairs are white, you could try changing the color to one that suits you. If we really wanted to we could make for example limegreen, pink and cyan selectable options in the main menu

**Comment by shaeeee** [comment]
@kimcodekill never said white didn't suit me. In any case I tested a shader to make the reticle have the inverted color of whatever is behind it, but I'm not good enough at HLSL to make that work, so I think white will cover the most cases.

**Comment by kimcodekill** [comment]
@shaeeee alright time to merge then i guess.

**Pull request merged**
