### PR TITLE
Audio

### PR DESCRIPTION
**Pull request by Viktorb9**
Okay, the big one. There's a lot of stuff in this one, and some things had to be done suboptimally because of time limits, but right now it is what it is. Hopefully everything works.

### CODE REVIEW

**Review by LatentGecko — DISMISSED** [review]
Alla ljud verkar höras o verkar funka bra nog för detta speltestet.

**Review by shaeeee — COMMENTED** [review]
When I stop walking with the mech the walk sound cuts off quite abruptly. Maybe it's possible to make it echo out more smoothly, kind of like the AutoRifle shots?

**Comment by Viktorb9** [comment]
Yes, for a while I had some code make sure that the whole audio clip played out. However it had a bug where in a rare cases it would continue playing after the player stopped until he moved again, so I let it be the way it is right now. Gunshots work great because the audio clip is played every time a bullet is shot, but unless there is a way to find out every time a step is taken it can't be done the same way.

**Review by LatentGecko — APPROVED** [review]
Alla ljud verkar höras o verkar funka bra nog för detta speltestet. Det kan finnas buggar o balansen inte är helt där men det räcker för speltestet. Balans speciellt är nåt man kan tweaka i oändligheter ändå.

**Pull request merged**
