### PR TITLE
Pause menu

### PR DESCRIPTION
**Pull request by kimcodekill**
Adds a pause menu :)

### CODE REVIEW

**Comment by ErikPilstrom** [comment]
I fixed the sound issues on the EnemyBase script in enemyRework now too, so should work correctly after merger too,

**Review by ErikPilstrom — COMMENTED** [review]
Everything seems to work well apart from mouse sense. I don't notice any difference when changing the sensitivity value in the menu.

**Comment by kimcodekill** [comment]
@ErikPilstrom have you pulled latest version?

**Review by ErikPilstrom — APPROVED** [review]
All good now!

Very nice change that minimum mouse sense is not quite 0, good change.

Previous issues fixed.

**Pull request merged**
