### PR TITLE
Implemented Erik's spread snippet for the player weapons

### PR DESCRIPTION
**Pull request by kimcodekill**

### CODE REVIEW

**Comment by kimcodekill** [comment]
Please play with both this and the old version, it doesnt feel very different from before but im not sure

**Review by shaeeee — DISMISSED** [review]
Works very well mechanically so I approve this, but the spread angles may need to be adjusted to be lower across the board to make it feel more like the old levels. Shotgun spread at the 30 meter mark felt a little excessive with the new system for example.

**Comment by ErikPilstrom** [comment]
It shouldn't feel very different, but it works a bit different under the hood and is likely to be more consistent. Above all, it's more precise mechanically and lets us set an exact value for the spread in degrees from the axis. So for the sniper, if we want to simulate the real world a bit more, instead of having literally no spread on the sniper when zoomed-in we could have like 1 degree of spread.

Enemy death being a bit wonky should be better now with the last fix to enemy branch, so try again, play around, and see what works.

**Review by ErikPilstrom — APPROVED** [review]
Looks like it works fine, spread feels pretty good, maybe a bit too small on AR but I think that's still fine.
Approved.

**Pull request merged**
