### PR TITLE
created new enemy classes

### PR DESCRIPTION
**Pull request by ErikPilstrom**
The beginning.

- Created three new Enemy subclasses named GruntDroid, EliteDroid, TurretDroid

### CODE REVIEW

**Comment by kimcodekill** [comment]
DRAFT <3

**Comment by ErikPilstrom** [comment]
Well, animations on enemies work and are fine. I still can't fix the crash bug. I have no idea what causes it or how to fix it. Game's worthless.

**Review by kimcodekill — DISMISSED** [review]
Yeah probably good enough

**Review by kimcodekill — APPROVED** [review]
japp

**Pull request merged**
