### PR TITLE
New main menu

### PR DESCRIPTION
**Pull request by Viktorb9**
Audio settings are pretty self-explanatory. Display settings require a build to work. Mouse sensitivity changes the camera sensitivity. All settings are stored in PlayerPrefs.

Anyway, the color of the menu can easily be changed in the MainMenu prefab, I thought green was good with our mech. Background is just a placeholder screenshot, not sure what we want there.

In addition to the menu I made the hud show carried and active weapon for clarity, and pickups that you can't pick up show the message that it's full.

### CODE REVIEW

**Review by kimcodekill — CHANGES_REQUESTED** [review]
Font is hard to read, lets change it to something more readable.
Sensitivity gets set to low by default, lets make it default to what it's been all through the project.

**Review by LatentGecko — CHANGES_REQUESTED** [review]
The background doesn't really look good, either remove it and make it plain or get a cool promo screenshot with the mech to put there.
The in-game UI for weapon selection is too obtrusive, lets make it less so maybe with icons.

**Review by kimcodekill — CHANGES_REQUESTED** [review]
Settings need to be manually modified to be saved. the default settings should be saved in playerprefs if their keys dont already exist. Otherwise the player spawns without sound and mouse settings.

**Review by kimcodekill — DISMISSED** [review]
new menu is neat

**Review by kimcodekill — APPROVED** [review]
yep seems fine

**Review by LatentGecko — APPROVED** [review]
👌🦎

very cool

**Pull request merged**
