### PR TITLE
Intro scene

### PR DESCRIPTION
**Pull request by LatentGecko**
This branch adds an intro cinematic to the game in form of a new scene to be played between the menu and the first level.

### CODE REVIEW

**Review by kimcodekill — CHANGES_REQUESTED** [review]
pls add fade in to level 1

**Review by ErikPilstrom — CHANGES_REQUESTED** [review]
- Delay on "Press space to skip text"
- Add a confirmation to skip after pressing space the first time, so that space has to be pressed a second time.
- Improve mood/feeling by adding a second sound track under the first that fades in when Scorthazan ships appear and reach a crescendo at the end.
- Do a fade in on level 1

**Review by Viktorb9 — COMMENTED** [review]
Shouldn't the audio be separated into music and voice groups?

**Comment by LatentGecko** [comment]
> Shouldn't the audio be separated into music and voice groups?

The audio is one file, cant be split into 2 different groups. But any such tweaks I'll do later in the updatedAudio branch.

**Review by shaeeee — DISMISSED** [review]
Clicking space after the "press space to confirm skip" text vanishes causes the animation to look fucky the next time "press space to confirm skip" appears

**Comment by LatentGecko** [comment]
Not doing fade in because of lag between scene transitions.
Disabling berp function in UI to have no animations instead of laggy animations.

Not fixing these because not much time and not that important.

**Review by kimcodekill — APPROVED** [review]
good enough, time constraint is bitch

**Review by ErikPilstrom — APPROVED** [review]
Good. Approved. Merge this bitch.

**Pull request merged**
