### PR TITLE
Mech anim2

### PR DESCRIPTION
**Pull request by ErikPilstrom**
this is just a test, please ignore

### CODE REVIEW

**Comment by ErikPilstrom** [comment]
Alright, seems to work.
- Branch adds updated Player prefab
- Animations for player mech with some particles

**Review by kimcodekill — CHANGES_REQUESTED** [review]
If these changes are intended to be ready for playtest then im sorry but it isnt enough if the player isnt implemented yet.

**Review by shaeeee — CHANGES_REQUESTED** [review]
Looks good but please remove the merge junk files

**Review by shaeeee — APPROVED** [review]
Ok, good. Transparency is struggling a little but its better than having the mech block the players line of sight completely, it'll have to do for now.

**Review by kimcodekill — APPROVED** [review]
I'm gonna say what @shaeeee said, it'll do for now.

**Pull request merged**
