### PR TITLE
Grounded Dashing and Afterburning

### PR DESCRIPTION
**Pull request by shaeeee**
This branch enables the usage of dash while grounded, and modifies the Y axis elevation limit to factor in dashing uphill. This effectively means that if you try to use an edge to dash against and bounce up, you cannot, but if you dash uphill you will be allowed to rise on the Y axis.

Below is an example on how the new elevation limitation system affects dashing:
Before:

After:

I'd like feedback on how the afterburner should be balanced.

### CODE REVIEW

**Review by kimcodekill — CHANGES_REQUESTED** [review]
Dashing on ground is good yesyes.
What I need is some DEVVY indicator on afterburner status. Just a bar or whatever, otherwise it feels awful.

Also please pull master as the noSliding changes might interfere with this ground dashing stuff.

**Review by LatentGecko — COMMENTED** [review]
This seems to work pretty well, I like it, dashing and dashing into slopes feels better. 
I'm quite indifferent to whether or not to have ground dash so if others want it I'm for it. 
But before implementing, there's a bug where when you're on a long slope like stairs and you dash up it, you get a bounce at the end of the dash.

**Review by kimcodekill — COMMENTED** [review]
Played around with it, starting to wonder if the airdash and grounddash should work different from each other. 
The air dash is understandably limited; you press once, it happens once, and that's fine. The ground dash however feels like the air dash x3 and it's not really an enjoyable experience to dash three times for the range you get with it. Maybe we should discuss turning the ground dash into a held action.

The UI is splendid and I couldn't find any other issues through playing with it. If this is what we want the grounded dash to be then yes, I consider this done and will approve.

**Review by ErikPilstrom — DISMISSED** [review]
Works well. I would say it feels fine, I don't think the grounded dash is an issue, it works sort of like a "dodge" and that was how I had envisioned it.

The slider is currently interactable, not sure it should be / needs to be, easy change.
image

The UI works, but could be made prettier. I think there is a way to use gradients in a slider, but it works for now. I will make a card on Trello for "prettifying" it, shouldn't stand in the way of this prq.

**Review by ErikPilstrom — DISMISSED** [review]
Mechanically, I think this is the one we want. Completely consistent, maximizes player freedom, feels great to use.

Number tweaking is irrelevant at this stage, we can alter the charge time as we see fit, might take some experimenting to find the right one.

**Review by ErikPilstrom — APPROVED** [review]
reeeeeeeeee ;)

**Review by kimcodekill — APPROVED** [review]
I'm into it. The ui element is in a bit of a weird place, but it definitely does the job.

**Pull request merged**
