### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by kimcodekill**
This should be the first pull request to be approved before any other pull requests. I'll personally close any other pull requests. This is important.

### CODE REVIEW

**Review by kimcodekill — COMMENTED** [review]
@shaeeee  ⭐

**Review by kimcodekill — COMMENTED** [review]
@LatentGecko ⭐

**Review by kimcodekill — COMMENTED** [review]
@ErikPilstrom  ⭐

**Review by kimcodekill — COMMENTED** [review]
@Viktorb9 ⭐

**Review by kimcodekill — COMMENTED** [review]
@HenrikHokby ⭐

**Review by LatentGecko — APPROVED** [review]
Lightmaps are gone, most of everything is cleaned up and/or reorganized and best of all, still seems working. Great!

**Comment by kimcodekill** [comment]
@LatentGecko extra ⭐

**Pull request merged**
