### PR TITLE
Weapon rebalance w18

### PR DESCRIPTION
**Pull request by kimcodekill**
YOOO yall need to check out these new guns! We've got:
- Sniper being bad unless scoped, during which it's 100% (yes you read that right) accurate.
- Rocket Launcher not being bad
- Shotgun not being a godgun anymore
- Autorifle being less spready and spammy

### CODE REVIEW

**Review by shaeeee — APPROVED** [review]
(❁´◡`❁)

**Comment by kimcodekill** [comment]
- need to tweak some stuff with the rockets and other things

**Review by ErikPilstrom — APPROVED** [review]
Generally good changes, no glaring issues and bugs, expect for the rocket launcher problems which you are aware of. I see not reason this can't be merged into master.

I especially like the changes to magazine size for the more powerful weapons, makes sense, make the balancing easier, and makes them intrinsically feel more powerful simply due to having less ammo per mag.

Approved.

**Review by LatentGecko — COMMENTED** [review]
Generally good changes, I like it. Guns feel much better.
But the auto rifle feels too overpowered at long range with this low spread. 
Lower spread works/feels nicely at the intended range but attempting to snipe with it is now way too easy. 
I think it should in some way be nerfed to not be as effective as it is at longer ranges.

**Review by Viktorb9 — COMMENTED** [review]
Great improvements, I don't really have much to add in addition to what's already been said. Just want to say that a nice addition would be that the auto rifle cools down when another weapon is equipped.

**Pull request merged**
