### PR TITLE
Drops

### PR DESCRIPTION
**Pull request by shaeeee**
This branch adds a system to let enemies drop loot. Classes implementing the lootable interface can specify what should be dropped according to some weights, and the system will spawn one of the specified loot table objects on enemy death events. This branch also includes a system for having spawned drops eventually disappear.

Currently only enemy turrets implement the lootable interface. My focus was on building the system itself, but if yall want me to specify the loot table for all enemies as well then give me a heads up.

### CODE REVIEW

**Review by Viktorb9 — COMMENTED** [review]
Seems good, the loot drops as it should and it all works. The test enemies' drops didn't expire, so I assume it's supposed to be that way, otherwise it needs to be looked over. Also, there's a conflict that needs to be resolved.

**Comment by kimcodekill** [comment]
yes pls define the loot tables
I'll check the branch out when im done with other things but yes pls do that

**Comment by shaeeee** [comment]
Added loot tables to all enemies.

**Review by kimcodekill — CHANGES_REQUESTED** [review]
First off: loot tables seem valid. Not sure how it'll play out but for future reference we might want to set the value depending on the weapon (i.e one ammo type being rarer than another)

However:
Pickups seem to slide around, lets put a material on them that makes them stick.
Pickups can be knocked around by the player, lets make them not collide with the player but just react to trigger entered to bring down confusion.
Pickups disappear far too quickly, lets set the timer to something like 10 seconds so the player has a chance to stay in flow without worrying about losing precious ammo

**Review by LatentGecko — COMMENTED** [review]
Looks and works well.
But, I think the drops despawn a bit too quickly. I like the idea of the drops being slidey and being able to be kicked around but if they're going to be sliding around the scene due to scene geometry like slopes it will be an issue and should probably be removed.

**Review by ErikPilstrom — CHANGES_REQUESTED** [review]
Please fix merge conflicts and then I will take a look :)

**Review by ErikPilstrom — APPROVED** [review]
Alright, seems good. Solid code, drops appear to be working as intended.

**Pull request merged**
