### PR TITLE
Atmosphere

### PR DESCRIPTION
**Pull request by LatentGecko**
Made changes to the graphics to the game.

Firstly we have a new skybox that is more cloudy and has a planet in it, then I tried to get the light and fog settings in the level to match it.
I adjusted all the lights in the level again for a different color and better intensity and better parameters. 
Added reflection probes to the tunnel in level 2 to make it darker and more natural. 
Added a subtle post processing to the game, tried to have it be subtle and add to the look, AO, Bloom, color etc. 
Adjusted bake settings for the final build in both levels. 

I also added water to the game and replaced the preexisting "blue blocks of "water"" with moving water, tried to get the water to look cartoony'ish to match the look of the rest of the game. 

I don't want to commit lightmap data with this so if you want to test how this looks you'll have to bake the light yourself with lower settings.

### CODE REVIEW

**Review by shaeeee — COMMENTED** [review]
I think some more color grading would simulate a more fitting GI according to the atmosphere color.
Provided below is two screens, one with your grading, the other with Lift moved into the orange range:
image
image

**Comment by LatentGecko** [comment]
> I think some more color grading would simulate a more fitting GI according to the atmosphere color.

The color of the game gets MUCH orange'ier after baking, hence I pulled back on my color grading post processing cause I thought it became too much. 

image

Theres a picture of it baked, it looks a bit more like what youre suggesting.

**Review by kimcodekill — CHANGES_REQUESTED** [review]
Skybox has an obvious seam.
Issue with trails being wonky on pickups bc motion blur, fix, remove or ignore. Whatever seems best.

**Review by shaeeee — DISMISSED** [review]
Looks good to me

**Review by kimcodekill — DISMISSED** [review]
Im into it.

**Review by kimcodekill — APPROVED** [review]
this version should be final

**Pull request merged**
