### PR TITLE
Level2fixgecko

### PR DESCRIPTION
**Pull request by LatentGecko**
Level 2 is finished, a bunch of sections have been revised due to feedback, enemy numbers are upped, pickups are less. Skybox and fog exitsts, lighting is lighted and also baked.

### CODE REVIEW

**Review by shaeeee — CHANGES_REQUESTED** [review]
image
First checkpoint is facing backwards, so you respawn looking away from where you are supposed to go.
Otherwise no complaints, looks good.

**Review by shaeeee — APPROVED** [review]
Checkpoints fixed, now I just need to fix the code behind them and we'll be all set.

**Comment by kimcodekill** [comment]
@shaeeee so after conflicts are resolved is it ready to be merged even though you "need to fix the code"? Will it be broken even though it's approved?

**Comment by shaeeee** [comment]
@kimcodekill 
If this prq is merged, also merging prq#96 will make them work. I approved this because this is a level design pull request, and does what it set out to do.

**Pull request closed without merging**
