### PR TITLE
some minor enemy improvements

### PR DESCRIPTION
**Pull request by ErikPilstrom**
This branch adds some requested features and improves on existing enemy features.
- Changed all enemies' attacks to be based on an equipped "Weapon" for each enemy, with setable values for attack range, damage, rate of fire, and spread.
- Weapon attacks fire HitEvents when the Player is hit, no more hardcoded attacks on player
- Weapon attack rays are drawn in the world using LineRenderer to visualize attacks on the player, both misses and hits
- Updates to enemy behaviour and states for improved consistency

### CODE REVIEW

**Review by kimcodekill — COMMENTED** [review]
Enemies a little too forgetful, on player going out of sightline: force them to remember last player position and travel there before going into search mode

**Review by kimcodekill — COMMENTED** [review]
Better, but wouldn't call this perfect yet.

1. Enemies shoot as soon as the player is within range. Would make sense if they at least had to rotate towards the player before they can shoot.
2. Enemies attack range is waay too low causing the enemy to do more chasing than shooting if the player is moving. viewRange - 5 worked for me but im not gonna say thats perfect.
3. Bullets are way too slow in projectile mode. Couldn't get the spread to work, but if there was spread i would prefer a raycast in every way.

**Comment by ErikPilstrom** [comment]
- Normalized input vector for spread to be consistent with other weapons when setting spread coefficient in inspector
- Added SerializedField attackLimitDegrees so that we can set the angle within which we want to allow and enemy to attack the player: 180 lets them attack freely in all angles, 0 prevents them from attacking at all.
-Marginally increased bullet projectile speed, can be easily changed in inspector on bulletV2 prefab to change behaviour

**Review by kimcodekill — DISMISSED** [review]
You might have to change some numbers and i would recommend doing so before merge, but i approve the systematic changes.

**Review by shaeeee — DISMISSED** [review]
Looks good to me.

**Review by shaeeee — APPROVED** [review]
Seems good

**Pull request merged**
