### PR TITLE
Pickups HUD text

### PR DESCRIPTION
**Pull request by Viktorb9**
This branch does contain some new designs for pickups (including health), but some problems arose after the enemy drops, so let's hold them back for now. Instead the main feature to add is a simple HUD text that pops up when you pick up pickups... It's not good looking (and hard to see a lot of the time), but hey it's better than nothing.

### CODE REVIEW

**Review by LatentGecko — COMMENTED** [review]
The text fades out way too fast, player won't really have time to read what they even picked up. 
Would probably be nice to make the font a bit bigger too, and if possible, add an outline component to the text so its never invisible due to environment.

**Review by shaeeee — CHANGES_REQUESTED** [review]
Everything looks good but I agree that some form of outline is needed for the text to enhance visibility.

**Comment by kimcodekill** [comment]
@Viktorb9 are you fixing this? otherwise ask for help.

**Comment by Viktorb9** [comment]
Okay I fiddled around with Textmeshpro and now it should be better

**Review by shaeeee — DISMISSED** [review]
(❁´◡`❁)

**Review by ErikPilstrom — DISMISSED** [review]
Looks good, just fix merge conflict and you can merge.

**Review by kimcodekill — APPROVED** [review]

**Pull request merged**
